#!/usr/bin/env bash

# Default Make flags
export CFLAGS='-Wall -O2'
export GOPATH="$HOME/go"
export PATH="$PATH:$HOME/go/bin"
export SUDO_ASKPASS=$HOME/scripts/dmenu-askpass

alias vimrc="vim $HOME/.vimrc"\
    nvimrc="nvim $HOME/.config/nvim/init.vim"\
    zshenv="$EDITOR $HOME/.zshenv"\
    zshrc="$EDITOR $HOME/.zshrc"\
    tmuxrc="$EDITOR $HOME/.tmux.conf"\
    aliasrc="$EDITOR $HOME/aliasrc"\
    mkpwd="head -c 500 /dev/urandom | tr -dc 'a-zA-Z0-9!@#%^&*_-' | head -c 14"\
    copy="xclip -selection clipboard"\
    gdiff="git diff"\
    ltxclear="rm *.fdb_latexmk *.fls *.log *.pgf-plot.gnuplot *.synctex.gz *.au *.fd"\
    passwords="nvim ~/.config/secrets.gpg"\
    cat=bat


source "$HOME/notes/.conf/config.sh"

vf() {
    $EDITOR $(find . -name $1)
}

NEWCFG="$HOME/.config/newcfg.vim"
alias e="nvim -u $NEWCFG"\
    erc="nvim -u $NEWCFG $NEWCFG"\
    vim="nvim -u /dev/null"
