#!/usr/bin/env bash

# Default Make flags
export CFLAGS='-Wall -O2'
export GOPATH="$HOME/go"

alias ls='ls --color'\
    lsa='ls -lah'

alias vimrc="vim $HOME/.vimrc"\
    nvimrc="nvim $HOME/.config/nvim/init.vim"\
    zshenv="$EDITOR $HOME/.zshenv"\
    zshrc="$EDITOR $HOME/.zshrc"\
    tmuxrc="$EDITOR $HOME/.tmux.conf"\
    aliasrc="$EDITOR $HOME/aliasrc"\
    mkpwd="head -c 500 /dev/urandom | tr -dc 'a-zA-Z0-9!@#%^&*_-' | head -c 14"\
    copy="xclip -selection clipboard"\
    vis="$EDITOR -S Session.vim"\
    gdiff="git diff"\
    fn='find . -name'\
    ltxclear="rm *.fdb_latexmk *.fls *.log *.pgf-plot.gnuplot *.synctex.gz *.au *.fd"\
    pwedit="nvim ~/.config/secrets.gpg"

vf() {
    $EDITOR $(find . -name $1)
}


