#!/usr/bin/env sh
# Enable dual screen
POSITION="--left-of"
LAPTOP="eDP1"

# EXTERNAL=$(xrandr -q | awk "/ connected/&&!/^${LAPTOP}/{print \$1}")
EXTERNAL=DP1


# Enable dual screen
    #xrandr --output "$EXTERNAL" --off --output "$LAPTOP" --auto
     xrandr --output $EXTERNAL --primary --mode 1920x1080 --output $LAPTOP $POSITION $EXTERNAL
